[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["npm install --production"]

[phases.build]
cmds = ["echo 'No build step required for Node.js'"]

[start]
cmd = "npm start"
