[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps"]

[phases.build]
cmds = ["echo 'Backend build complete - no build step needed'"]

[start]
cmd = "npm start"
